# Site
name: "Tesselo"
title: "The Guts of Tesselo"
description: "The remains of a newspace startup."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  remi:
    name: Remi
    display_name: RÃ©mi
    avatar: 'assets/images/remi.jpg'
    web: https://pt.linkedin.com/in/remicharpentier
    twitter: https://pt.linkedin.com/in/remicharpentier
    description: "Co-Founder and CEO of Tesselo. Has helped building the buisness side of Tesselo by turning satellite imagery and artificial intelligence into environmental and business insights. "

  daniel:
    name: Daniel
    display_name: Daniel
    avatar: 'assets/images/daniel.png'
    web: https://github.com/yellowcap
    twitter: https://github.com/yellowcap
    description: "Co-Founder and CTO of Tesselo. Has helped building the tech team and developing the platform for AI on Satellite imagery used by Tesselo for its projects."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
